name: psc-label
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - pip=24.2
  - ipykernel=6.29.5
  - pip:
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - pytest==8.3.2
    - pypdf==4.3.1
    - langchain==0.2.14
    - langchain_community==0.2.12
    - openai==1.41.0
    - ipywidgets==8.1.3
    - openpyxl=3.1.5
    - omegaconf==2.3.0
    # - streamlit==1.37.1
    # - marker-pdf==0.2.16
    # - torch==2.4.0
    # - transformers==4.44.0